/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Moveit
{
    public class MoveGroupAction : Message
    {
        public const string RosMessageName = "moveit_msgs/MoveGroupAction";

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public MoveGroupActionGoal action_goal { get; set; }
        public MoveGroupActionResult action_result { get; set; }
        public MoveGroupActionFeedback action_feedback { get; set; }

        public MoveGroupAction()
        {
            this.action_goal = new MoveGroupActionGoal();
            this.action_result = new MoveGroupActionResult();
            this.action_feedback = new MoveGroupActionFeedback();
        }

        public MoveGroupAction(MoveGroupActionGoal action_goal, MoveGroupActionResult action_result, MoveGroupActionFeedback action_feedback)
        {
            this.action_goal = action_goal;
            this.action_result = action_result;
            this.action_feedback = action_feedback;
        }
    }
}
