/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Moveit
{
    public class PickupAction : Message
    {
        public const string RosMessageName = "moveit_msgs/PickupAction";

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public PickupActionGoal action_goal { get; set; }
        public PickupActionResult action_result { get; set; }
        public PickupActionFeedback action_feedback { get; set; }

        public PickupAction()
        {
            this.action_goal = new PickupActionGoal();
            this.action_result = new PickupActionResult();
            this.action_feedback = new PickupActionFeedback();
        }

        public PickupAction(PickupActionGoal action_goal, PickupActionResult action_result, PickupActionFeedback action_feedback)
        {
            this.action_goal = action_goal;
            this.action_result = action_result;
            this.action_feedback = action_feedback;
        }
    }
}
