/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Actionlib;

namespace RosSharp.RosBridgeClient.MessageTypes.Moveit
{
    public class PickupActionResult : Message
    {
        public const string RosMessageName = "moveit_msgs/PickupActionResult";

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public Header header { get; set; }
        public GoalStatus status { get; set; }
        public PickupResult result { get; set; }

        public PickupActionResult()
        {
            this.header = new Header();
            this.status = new GoalStatus();
            this.result = new PickupResult();
        }

        public PickupActionResult(Header header, GoalStatus status, PickupResult result)
        {
            this.header = header;
            this.status = status;
            this.result = result;
        }
    }
}
