/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Moveit
{
    public class PlaceAction : Message
    {
        public const string RosMessageName = "moveit_msgs/PlaceAction";

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public PlaceActionGoal action_goal { get; set; }
        public PlaceActionResult action_result { get; set; }
        public PlaceActionFeedback action_feedback { get; set; }

        public PlaceAction()
        {
            this.action_goal = new PlaceActionGoal();
            this.action_result = new PlaceActionResult();
            this.action_feedback = new PlaceActionFeedback();
        }

        public PlaceAction(PlaceActionGoal action_goal, PlaceActionResult action_result, PlaceActionFeedback action_feedback)
        {
            this.action_goal = action_goal;
            this.action_result = action_result;
            this.action_feedback = action_feedback;
        }
    }
}
